import 'package:dar_com/models/details_item/details_item_model.dart';

class DetailsItemPreferences{
  List<DetailItemModel> item=[
    DetailItemModel(
    urlImages: ['assets/images/apartments.jpg',
    'assets/images/villa.jpg',
    'assets/images/villa.jpg',
      'assets/images/shops.jpg'],
    info: 'this property is amazing for yuo '
        'you will fell comfortable with it..it has a nice view on sea.. ',
    location: 'New York',
    numRooms: 5,
      size: 150.44,
      price: 1200,
      numPathRooms: 4,
      dimensionOfCity: 100,
      dimensionOfSchool: 30,
      netSubscription: true,
      phoneSubscription: true,
  ),
    DetailItemModel(
      urlImages: ['assets/images/apartments.jpg',
        'assets/images/villa.jpg',
        'assets/images/villa.jpg',
        'assets/images/shops.jpg'],
      info: 'this property is amazing for yuo '
          'you will fell comfortable with it..it has a nice view on sea.. ',
      location: 'chikagho',
      numRooms: 9,
      size: 170.8,
      price: 1500.3,
      numPathRooms: 4,
      dimensionOfCity: 100,
      dimensionOfSchool: 30,
      netSubscription: false,
      phoneSubscription: true,
    ),
    DetailItemModel(
      urlImages: ['assets/images/apartments.jpg',
        'assets/images/villa.jpg',
        'assets/images/villa.jpg',
        'assets/images/shops.jpg'],
      info: 'this property is amazing for yuo '
          'you will fell comfortable with it..it has a nice view on sea.. ',
      location: 'New York',
      numRooms:10,
      size: 80.4,
      price: 500.55,
      numPathRooms: 4,
      dimensionOfCity: 20,
      dimensionOfSchool: 10,
      netSubscription: true,
      phoneSubscription: true,
    ),
    DetailItemModel(
      urlImages: ['assets/images/apartments.jpg',
        'assets/images/villa.jpg',
        'assets/images/villa.jpg',
        'assets/images/shops.jpg'],
      info: 'this property is amazing for yuo '
          'you will fell comfortable with it..it has a nice view on sea.. ',
      location: 'Seoul',
      numRooms: 2,
      size: 49.77,
      price: 300.4,
      numPathRooms: 4,
      dimensionOfCity: 150,
      dimensionOfSchool: 70,
      netSubscription: false,
      phoneSubscription: false,
    ),
    DetailItemModel(
      urlImages: ['assets/images/apartments.jpg',
        'assets/images/villa.jpg',
        'assets/images/villa.jpg',
        'assets/images/shops.jpg'],
      info: 'this property is amazing for yuo '
          'you will fell comfortable with it..it has a nice view on sea.. ',
      location: 'korea',
      numRooms: 9,
      size: 90.3,
      price: 600,
      numPathRooms: 4,
      dimensionOfCity: 100,
      dimensionOfSchool: 30,
      netSubscription: true,
      phoneSubscription: false,
    ),
    DetailItemModel(
      urlImages: ['assets/images/apartments.jpg',
        'assets/images/villa.jpg',
        'assets/images/villa.jpg',
        'assets/images/shops.jpg'],
      info: 'this property is amazing for yuo '
          'you will fell comfortable with it..it has a nice view on sea.. ',
      location: 'Sedny',
      numRooms: 10,
      size: 180.7,
      price: 2100,
      numPathRooms: 4,
      dimensionOfCity: 90,
      dimensionOfSchool: 25,
      netSubscription: true,
      phoneSubscription: true,
    ),
  ];
}